"""Render a notation sequence to a clean vector image (SVG, optional PNG).

SVG is generated by plain string templating so the core renderer needs **no**
dependencies. PNG rasterisation is optional and uses ``cairosvg`` if installed
(``pip install 'capoeira-music[render]'``); otherwise only the SVG is written.

Vector (rather than AI-generated) images were chosen deliberately: the symbols
are exact, reproducible, diffable, and cheap to regenerate from course.json.
"""
from __future__ import annotations

from pathlib import Path
from typing import Sequence

from .notation import SYMBOLS, syllables_for

# Layout constants (px).
CELL = 90
SYM = 46          # symbol half-extent reference
PAD_TOP = 70      # room for the title
PAD_BOTTOM = 46   # room for the syllable labels
MARGIN = 30
STROKE = 4
COLOR = "#1a2b6b"     # ink blue, matching the handwritten notes
ACCENT = "#b5341d"


def _symbol_svg(symbol: str, cx: float, cy: float) -> str:
    """Return SVG markup drawing one symbol centred at (cx, cy)."""
    h = SYM / 2
    if symbol == "X":
        return (
            f'<line x1="{cx-h}" y1="{cy-h}" x2="{cx+h}" y2="{cy+h}" '
            f'stroke="{COLOR}" stroke-width="{STROKE}" stroke-linecap="round"/>'
            f'<line x1="{cx-h}" y1="{cy+h}" x2="{cx+h}" y2="{cy-h}" '
            f'stroke="{COLOR}" stroke-width="{STROKE}" stroke-linecap="round"/>'
        )
    if symbol in ("▽", "△", "▲", "▽ˣ"):
        if symbol in ("▽", "▽ˣ"):  # down-pointing triangle (open low tone / salto)
            pts = f"{cx-h},{cy-h} {cx+h},{cy-h} {cx},{cy+h}"
        else:  # up-pointing triangle (pressed high / preso, or strong salto)
            pts = f"{cx},{cy-h} {cx-h},{cy+h} {cx+h},{cy+h}"
        fill = COLOR if symbol == "▲" else "none"
        markup = (
            f'<polygon points="{pts}" fill="{fill}" stroke="{COLOR}" '
            f'stroke-width="{STROKE}" stroke-linejoin="round"/>'
        )
        if symbol == "▽ˣ":  # accent / hammeron: small superscript x
            sx, sy = cx + h, cy - h
            d = 7
            markup += (
                f'<line x1="{sx-d}" y1="{sy-d}" x2="{sx+d}" y2="{sy+d}" '
                f'stroke="{ACCENT}" stroke-width="3" stroke-linecap="round"/>'
                f'<line x1="{sx-d}" y1="{sy+d}" x2="{sx+d}" y2="{sy-d}" '
                f'stroke="{ACCENT}" stroke-width="3" stroke-linecap="round"/>'
            )
        return markup
    # Unknown symbol: render the raw glyph as text so nothing is silently lost.
    return (
        f'<text x="{cx}" y="{cy+8}" font-size="34" text-anchor="middle" '
        f'fill="{COLOR}">{_escape(symbol)}</text>'
    )


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    )


def build_svg(
    sequence: Sequence[str],
    *,
    title: str = "",
    syllables: str | None = None,
) -> str:
    """Build the SVG document string for one notation sequence."""
    n = max(len(sequence), 1)
    width = MARGIN * 2 + CELL * n
    height = PAD_TOP + CELL + PAD_BOTTOM
    cy = PAD_TOP + CELL / 2
    # The free-form `syllables` (e.g. the instructor's spoken phrase) is shown as
    # a subtitle; per-symbol labels always come from each symbol's canonical
    # syllable so they stay aligned even when the spoken count differs.
    spoken = syllables if syllables is not None else syllables_for(sequence)

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">',
        f'<rect width="{width}" height="{height}" fill="#fbfaf6"/>',
    ]
    if title:
        parts.append(
            f'<text x="{width/2}" y="36" font-size="26" font-family="Georgia, serif" '
            f'font-weight="bold" text-anchor="middle" fill="{COLOR}">{_escape(title)}</text>'
        )
    if spoken:
        parts.append(
            f'<text x="{width/2}" y="58" font-size="16" font-family="Georgia, serif" '
            f'font-style="italic" text-anchor="middle" fill="{COLOR}">'
            f'“{_escape(spoken)}”</text>'
        )
    for i, symbol in enumerate(sequence):
        cx = MARGIN + CELL * i + CELL / 2
        parts.append(_symbol_svg(symbol, cx, cy))
        label = SYMBOLS.get(symbol, {}).get("syllable") or ""
        if label:
            parts.append(
                f'<text x="{cx}" y="{height-16}" font-size="20" font-family="Georgia, serif" '
                f'text-anchor="middle" fill="{COLOR}">{_escape(label)}</text>'
            )
    parts.append("</svg>")
    return "\n".join(parts)


def render_sequence(
    sequence: Sequence[str],
    out_svg: str | Path,
    *,
    title: str = "",
    syllables: str | None = None,
    out_png: str | Path | None = None,
) -> dict[str, str]:
    """Write the SVG (and PNG if cairosvg is available). Returns written paths."""
    out_svg = Path(out_svg)
    out_svg.parent.mkdir(parents=True, exist_ok=True)
    svg = build_svg(sequence, title=title, syllables=syllables)
    out_svg.write_text(svg)
    written = {"svg": str(out_svg)}

    if out_png is not None:
        try:
            import cairosvg  # type: ignore
        except ModuleNotFoundError:
            return written  # SVG only; PNG needs the [render] extra
        out_png = Path(out_png)
        out_png.parent.mkdir(parents=True, exist_ok=True)
        cairosvg.svg2png(bytestring=svg.encode("utf-8"), write_to=str(out_png), scale=2.0)
        written["png"] = str(out_png)
    return written
